#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-oss-parents
Version  : 38
Release  : 3
URL      : https://github.com/sonatype/oss-parents/archive/forge-parent-38.tar.gz
Source0  : https://github.com/sonatype/oss-parents/archive/forge-parent-38.tar.gz
Source1  : https://repo1.maven.org/maven2/com/fasterxml/oss-parent/4/oss-parent-4.pom
Source2  : https://repo1.maven.org/maven2/org/sonatype/forge/forge-parent/10/forge-parent-10.pom
Source3  : https://repo1.maven.org/maven2/org/sonatype/forge/forge-parent/11/forge-parent-11.pom
Source4  : https://repo1.maven.org/maven2/org/sonatype/forge/forge-parent/12/forge-parent-12.pom
Source5  : https://repo1.maven.org/maven2/org/sonatype/forge/forge-parent/3/forge-parent-3.pom
Source6  : https://repo1.maven.org/maven2/org/sonatype/forge/forge-parent/4/forge-parent-4.pom
Source7  : https://repo1.maven.org/maven2/org/sonatype/forge/forge-parent/5/forge-parent-5.pom
Source8  : https://repo1.maven.org/maven2/org/sonatype/forge/forge-parent/6/forge-parent-6.pom
Source9  : https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/6/oss-parent-6.pom
Source10  : https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom
Source11  : https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom
Source12  : https://repo1.maven.org/maven2/org/sonatype/spice/spice-parent/10/spice-parent-10.pom
Source13  : https://repo1.maven.org/maven2/org/sonatype/spice/spice-parent/12/spice-parent-12.pom
Source14  : https://repo1.maven.org/maven2/org/sonatype/spice/spice-parent/15/spice-parent-15.pom
Source15  : https://repo1.maven.org/maven2/org/sonatype/spice/spice-parent/16/spice-parent-16.pom
Source16  : https://repo1.maven.org/maven2/org/sonatype/spice/spice-parent/17/spice-parent-17.pom
Source17  : https://repo1.maven.org/maven2/org/sonatype/spice/spice-parent/18/spice-parent-18.pom
Source18  : https://repo1.maven.org/maven2/org/sonatype/spice/spice-parent/20/spice-parent-20.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-oss-parents-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-oss-parents package.
Group: Data

%description data
data components for the mvn-oss-parents package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/oss-parent/4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/oss-parent/4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/forge/forge-parent/10
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/forge/forge-parent/10

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/forge/forge-parent/11
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/forge/forge-parent/11

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/forge/forge-parent/12
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/forge/forge-parent/12

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/forge/forge-parent/3
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/forge/forge-parent/3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/forge/forge-parent/4
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/forge/forge-parent/4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/forge/forge-parent/5
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/forge/forge-parent/5

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/forge/forge-parent/6
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/forge/forge-parent/6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/oss/oss-parent/6
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/oss/oss-parent/6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/oss/oss-parent/7
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/oss/oss-parent/7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/oss/oss-parent/9
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/oss/oss-parent/9

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/spice/spice-parent/10
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/spice/spice-parent/10

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/spice/spice-parent/12
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/spice/spice-parent/12

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/spice/spice-parent/15
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/spice/spice-parent/15

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/spice/spice-parent/16
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/spice/spice-parent/16

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/spice/spice-parent/17
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/spice/spice-parent/17

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/spice/spice-parent/18
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/spice/spice-parent/18

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/spice/spice-parent/20
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/spice/spice-parent/20


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/fasterxml/oss-parent/4/oss-parent-4.pom
/usr/share/java/.m2/repository/org/sonatype/forge/forge-parent/10/forge-parent-10.pom
/usr/share/java/.m2/repository/org/sonatype/forge/forge-parent/11/forge-parent-11.pom
/usr/share/java/.m2/repository/org/sonatype/forge/forge-parent/12/forge-parent-12.pom
/usr/share/java/.m2/repository/org/sonatype/forge/forge-parent/3/forge-parent-3.pom
/usr/share/java/.m2/repository/org/sonatype/forge/forge-parent/4/forge-parent-4.pom
/usr/share/java/.m2/repository/org/sonatype/forge/forge-parent/5/forge-parent-5.pom
/usr/share/java/.m2/repository/org/sonatype/forge/forge-parent/6/forge-parent-6.pom
/usr/share/java/.m2/repository/org/sonatype/oss/oss-parent/6/oss-parent-6.pom
/usr/share/java/.m2/repository/org/sonatype/oss/oss-parent/7/oss-parent-7.pom
/usr/share/java/.m2/repository/org/sonatype/oss/oss-parent/9/oss-parent-9.pom
/usr/share/java/.m2/repository/org/sonatype/spice/spice-parent/10/spice-parent-10.pom
/usr/share/java/.m2/repository/org/sonatype/spice/spice-parent/12/spice-parent-12.pom
/usr/share/java/.m2/repository/org/sonatype/spice/spice-parent/15/spice-parent-15.pom
/usr/share/java/.m2/repository/org/sonatype/spice/spice-parent/16/spice-parent-16.pom
/usr/share/java/.m2/repository/org/sonatype/spice/spice-parent/17/spice-parent-17.pom
/usr/share/java/.m2/repository/org/sonatype/spice/spice-parent/18/spice-parent-18.pom
/usr/share/java/.m2/repository/org/sonatype/spice/spice-parent/20/spice-parent-20.pom
